#!/usr/bin/env python3

from glob import glob
from datetime import datetime


def load_logs():
    logs = dict()
    for filename in glob("/var/log/httpd/ssl_mgb_log*"):
        for line in open(filename, "r").read().splitlines():
            dt, _, ip, mgb, query = line.split(" ", 4)
            if query == "-":
                continue
            dt = dt[1:]
            dtobj = datetime.strptime(dt, "%d/%b/%Y:%H:%M:%S")
            logs[(dtobj, ip)] = (mgb, query)
    return logs


def annotate_calcium(logs):
    for line in (
        open("/var/www/cgi-bin/CalciumDir40/data/CalciumAuditLog", "rb")
        .read()
        .decode("ascii")
        .split("\n")
    ):
        try:
            d, t, ip, action = line.split(" ", 3)
            dtobj = datetime.strptime(" ".join((d, t)), "%Y/%m/%d %H:%M:%S")
        except ValueError:
            continue
        try:
            match = logs[(dtobj, ip)]
        except KeyError:
            match = ("?", "?")
        print(f"{match[0]} {line} # {match[1]}")


if __name__ == "__main__":
    logs = load_logs()
    annotate_calcium(logs)
