#!/bin/bash
# Extremly simplistic tool to merge one BIDS directory into another

if [ "$#" -ne 2 ] || ! [ -d "$1" ] || ! [ -d "$2" ]; then
  echo "Usage: $0 SOURCEDIR DESTDIR" >&2
  exit 1
fi

SOURCE=$1
DEST=$2

for d in ${SOURCE} ${DEST}; do
  # is this even nominally a BIDS folder?
  if ! [ -e "${d}"/dataset_description.json ]; then
    echo "${d} doesn't seem like a BIDS folder to me." >&2
    echo "Exiting, out of an abundance of caution." >&2
    exit 1
  fi
done

rsync -a --remove-source-files "${SOURCE}"/ "${DEST}"/
find "${SOURCE}" -depth -type d -empty -delete
