#!/bin/bash
set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run via sudo"
   exit 1
fi

if [ $# -ne 2 ]
  then
    echo "Usage: $0 newusername emailaddress"
    exit 1
fi

U=$1
E=$2

/cm/local/apps/cmd/bin/cmsh -c "user; add ${U}; set loginshell /bin/tcsh; set email $E ; set password; commit;"
mkdir /data/$U
cp /home/proto/.cshrc /home/proto/.cshrc.local /home/$U
chown -R $U:$U /home/$U /data/$U
echo Now please run "su - $U" and make sure that worked.
echo Important: tell Daniel to add /data/$U to backups.
