#!/bin/bash
set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run via sudo"
   exit 1
fi

if [ $# -ne 2 ]
  then
    echo "Usage: $0 newusername MGBID"
    exit 1
fi

U=$1
MGBID=$2

output=$(ldapsearch -y ~ddrucker/.ldpass -LLL -H ldap://ldap.partners.org:389 -D cn=so175,cn=users,dc=partners,dc=org -b"cn=users,dc=partners,dc=org" "(cn=$MGBID)" mail displayName)

if [ -z "$output" ]; then
    displayName=NOT-FOUND
    mail=NOT-FOUND
else
    displayName=$(echo "$output" | grep -i displayName | sed 's/displayName: //')
    mail=$(echo "$output" | grep -i mail | sed 's/mail: //' | tr 'A-Z' 'a-z')
fi
echo "Name: $displayName"
echo "Mail: $mail"

echo If these are incorrect, control-c now. Otherwise, hit return.
read

echo /cm/local/apps/cmd/bin/cmsh -c "user; add ${U}; set loginshell /bin/tcsh; set email $mail ; set surname $MGBID ; set commonname \"$displayName\" ; set password; commit;"

chown -R $U:$U /home/$U

cp /home/proto/.cshrc /home/proto/.cshrc.local /home/$U
cp /home/proto/.bash_profile /home/$U
chown $U:$U /home/$U/.cshrc* /home/$U/.bash*

## create nisaba dataset
API_KEY=$(cat ~ddrucker/truenas/apikey.txt)
API_URL="https://nisaba.mclean.harvard.edu/api/v2.0"
POOL_DATASET_PATH="chlorine/cluster-n/$U"

curl --insecure -H "Authorization: Bearer $API_KEY" -X POST "${API_URL}/pool/dataset" -d '{"name":"'${POOL_DATASET_PATH}'"}'
curl --insecure -H "Authorization: Bearer $API_KEY" -X POST "${API_URL}/sharing/nfs" \
     -d '{
  "paths": [   "/mnt/'${POOL_DATASET_PATH}'"  ],
  "hosts": [   "x5backup.mclean.harvard.edu"  ],
  "maproot_user": "root",
  "networks": [   "172.16.4.0/24", "172.17.4.0/24"  ]
 }'


## mount nisaba dataset
MOUNT_POINT="/data/$U"
cmsh -c "device; use micc; fsmounts; add ${MOUNT_POINT} ; set device nisaba.tengbenet.cluster:/mnt/${POOL_DATASET_PATH} ; set filesystem nfs; commit; commit"

while !  mount | grep "${POOL_DATASET_PATH} on"
do
    echo waiting for mount of $U
    sleep 5
done

chmod 775 ${MOUNT_POINT}
chown $U:$U ${MOUNT_POINT}

cmsh -c "category ; use universal; fsmounts; add ${MOUNT_POINT} ; set device nisaba.tengbenet.cluster:/mnt/${POOL_DATASET_PATH} ; set filesystem nfs; commit; commit; commit;"

echo Now please run "su - $U" and make sure that worked.
echo
echo "Next as root ON MICKEY run:"
echo "~ddrucker/truenas/mountpoint-for-mickey $U"
