#!/bin/bash
set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run via sudo"
   exit 1
fi

if [ $# -ne 2 ]
  then
    echo "Usage: $0 group user"
    exit 1
fi

cmsh -c "group ; append $1 members $2 ; commit"
sleep 2
sss_cache -E

