#!/bin/bash

baculacheck () {
    HOST=$1
    RPATH=$2
    FILESET=$3
    echo === The following ${RPATH} dirs have no backup job in ${FILESET} ===
    ssh ${HOST} "find ${RPATH} -not -name '.*' -maxdepth 1 -mindepth 1 -type d " | sort  > /tmp/actually-have

    if [[ ${HOST} == "micc" ]]; then
	sed s,/data/,/net/nisaba.mclean.harvard.edu/mnt/chlorine/cluster-n/, /tmp/actually-have | sponge /tmp/actually-have
    fi

    ssh x5backup cat /opt/bacula/etc/conf.d/Director/x5backup-dir/Fileset/${FILESET} \
        | grep " File =" \
        | cut -d\" -f2 \
        | sort > /tmp/have-jobs
    comm -23 /tmp/actually-have /tmp/have-jobs
}

baculacheck x5backup /durga durga\*
baculacheck x5backup /durga/data durga-data\*
baculacheck x5backup /durga/newcamdl durga-newcamdl\*
baculacheck x5backup /durga/CDASR/anl/exp3 durga-CDASR-anl-exp3\*
baculacheck x5backup /durga/CDASR/anl2/exp4 durga-CDASR-anl2-exp4\*
baculacheck micc /data micc-data\*

echo Done.
