#!/bin/bash
set -e

DAYS=${1:-30}
DIRS=$(find /data/fmriprep-workdir/*  -maxdepth 0 -ctime +${DAYS})
if [ -z "$DIRS" ]; then
    echo "Nothing to do." >&2
    exit;
fi
RMDIRS=$(find  /data/fmriprep-workdir/* -maxdepth 0 -ctime +${DAYS} -exec echo rm -rf {} \& \;)

echo -e "Ready for cleanup on $HOSTNAME: \n\n${RMDIRS}\ndisown -a\n" | Mail -s "pipeline cleanup" ddrucker@mclean.harvard.edu 
