#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run via sudo"
   exit 1
fi

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 MGBid sharename mountpoint"
    exit 1
fi

MGBID=$1
SHARENAME=$2
MOUNTPOINT=$3

case $(basename $0) in
    sfamount )
        SERVER=cifs2.partners.org
        if [[ $SHARENAME != *$ ]]; then
            SHARENAME="${SHARENAME}\$"
        fi
        ;;
    nisabamount )
        SERVER=nisaba
        ;;
    durgamount )
        SERVER=durga.mclean.harvard.edu
        ;;
    * )
        echo "Call me as sfamount, nisabamount, or durgamount, please."
        exit 1
        ;;
esac


if [ ! -d "$MOUNTPOINT" ]; then
    echo "$MOUNTPOINT" must be an empty directory
    exit 1
fi
if ls -1qA "$MOUNTPOINT" | grep -q . ; then
    echo "$MOUNTPOINT" must be an empty directory
    exit 1
fi
if [[ $SERVER != nisaba ]]; then
    echo -e "\nIMPORTANT NOTE: ${SERVER} mounts are NOT accessible from compute nodes!\n"
fi

echo -n "Going to mount //${SERVER}/${SHARENAME} on $(readlink -f $MOUNTPOINT) as $MGBID.  OK? (y/n): "
read -r answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo Please enter your MGB password...
    mount -t cifs -o vers=3.0,sec=ntlmv2i,domain=PARTNERS,username="$MGBID",uid="$SUDO_USER" //${SERVER}/"$SHARENAME" "$MOUNTPOINT"
else
    echo Aborted.
fi

