#!/bin/bash

singularity run -c \
  -B /home/ddrucker/mictools:/mictools:ro \
  -B /data/ddrucker/dicomin:/dicomin \
  /cm/shared/singularity/images/dcm.sif \
     storescp --output-directory /dicomin \
              --verbose \
              --sort-on-patientname \
              --eostudy-timeout 10 \
              --aetitle MICC \
              --exec-on-eostudy '/mictools/micc-receiver-eostudy #p' \
              11050
