#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run via sudo"
   exit 1
fi

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 MGBid sharename mountpoint"
    exit 1
fi

CREDFILE=$(getent passwd $SUDO_USER | cut -d: -f6)/.cred
function finish {
    rm -f $CREDFILE
}
trap finish EXIT

MGBID=$1
SHARENAME=$2
MOUNTPOINT=$3

SERVER=nisaba

if [ ! -d "$MOUNTPOINT" ]; then
    echo "$MOUNTPOINT" must be an empty directory
    exit 1
fi
if ls -1qA "$MOUNTPOINT" | grep -q . ; then
    echo "$MOUNTPOINT" must be an empty directory
    exit 1
fi

nodes="1 2 3 4"
nodename=mickey-node
echo "             ==== ATTENTION ===="
echo "nisabamount mounts a Nisaba SMB share on Mickey"
echo "and its compute nodes, for data access convenience."
echo "The SMB protocol can be slow to commit files to disk,"
echo "which means it is NOT APPROPRIATE FOR USE in running"
echo "certain types of jobs, especially fmriprep and FSL."
echo


echo -n "Going to mount //${SERVER}/${SHARENAME} on $(readlink -f $MOUNTPOINT) as $MGBID.  OK? (y/n): "
read -r answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    read -s -p "MGB password: " MGBPASS
    echo
    touch $CREDFILE
    chmod 400 $CREDFILE
    echo -e "username=$MGBID\npassword=$MGBPASS\ndomain=PARTNERS\n" > $CREDFILE
    
    mount -t cifs -o vers=3.0,sec=ntlmv2i,credentials=$CREDFILE,uid="$SUDO_USER" //${SERVER}/"$SHARENAME" "$MOUNTPOINT"
    MOUNTPOINT=$(realpath $MOUNTPOINT)
    for i in $nodes ; do
	echo mounting ${nodename}${i}
	sudo -u $SUDO_USER ssh ${nodename}${i} sudo /usr/local/bin/nisabamount-node "$SHARENAME" "$MOUNTPOINT" "$SUDO_USER" "$CREDFILE" 
    done
else
    echo Aborted.
fi

