#!/usr/bin/env python2 

import os
import sys
import SimpleHTTPServer
import SocketServer
import signal

def handler(signum, frame):
    print 'Exiting after 24 hours...'
    sys.exit(1)
signal.signal(signal.SIGALRM, handler)
signal.alarm(24*60*60)

try:
    if sys.argv[1].startswith('/'):
        filepath = sys.argv[1]
    else:
        filepath = os.getcwd() + '/' + sys.argv[1]
except IndexError:
    filepath = os.getcwd() 

os.chdir('/')

httpd = SocketServer.TCPServer(('', 0), SimpleHTTPServer.SimpleHTTPRequestHandler)

print 'Go to:      http://micc.mclean.harvard.edu:' + str(httpd.socket.getsockname()[1]) + filepath
print '(In Terminal, you can right-click the above and select Open URL.)'
print 'Please type Control-c when you are done.'
httpd.serve_forever()
