#!/usr/bin/env python3

import subprocess
import random
import socket
import getpass
import time
import signal
import sys
import os

# this is a wrapper around https://github.com/9001/copyparty/


def find_free_port():
    while True:
        port = random.randint(20000, 60000)
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("", port))
                return port
            except OSError:
                continue


def generate_password():
    return str(random.randint(100000, 999999))


def timeout_handler(signum, frame):
    print("\n24 hour timeout reached. Terminating server.")
    sys.exit(0)


def main():
    signal.signal(signal.SIGALRM, timeout_handler)
    signal.alarm(24 * 60 * 60)

    # Set environment variables for copyparty
    os.environ['PRTY_NO_CFSSL'] = '1'

    port = find_free_port()
    username = getpass.getuser()
    password = generate_password()

    cmd = [
        "copyparty-sfx.py",
        "-q",
        "-p",
        str(port),
        "--cert",
        "/home/ddrucker/mictools/everything-mickey.mclean.harvard.edu.pem",
        "--xdev",
        "--xvol",
        "-nb",
        "--no-lifetime",
        "-a",
        f"{username}:{password}",
        "-v",
        f".:::A,{username}",
    ]

    process = subprocess.Popen(cmd)

    time.sleep(1)

    print(
        f"""


Your server is running at:
    https://mickey.mclean.harvard.edu:{port}/

Login with the password {password}
(username doesn't matter!)

You can upload files by dragging them in.

Press control-c to exit.

"""
    )

    try:
        # Wait for the process to complete
        process.wait()
    except KeyboardInterrupt:
        print("\nShutting down server...")
        process.terminate()
        process.wait()


if __name__ == "__main__":
    main()
