#!/usr/bin/python3

import os
import sys
import errno
from shutil import copyfile
from glob import glob

if len(sys.argv) != 2:
    print("Usage: copy-qc-to-in s_YYYYMMDD_NN")
    sys.exit(1)

source = "94t"
scan = sys.argv[1]

year = scan[2:6]

pat = f"/{source}/studies_{year}/{scan}/mclean_niftis/{scan}*epi*nii"
matches = glob(pat)
if not matches:
    print(f"No matches for {pat}")
    sys.exit(1)

print(f"{pat} matched:")
for match in matches:
    print(f"    {match}")

if len(matches) != 1:
    print(f"Expected 1 match, got {len(matches)} instead.")
    sys.exit(1)

bids = f"/qc/mriqc/in/{source}/{scan}"

try:
    os.makedirs(f"{bids}/sub-qc/func")
except OSError as e:
    if e.errno != errno.EEXIST:
        raise

open(f"{bids}/dataset_description.json", "w").write(
    """\
{
"Name": "none",
"BIDSVersion": "1.2.0",
"Authors": ["x"]
}
"""
)

copyfile(matches[0], f"{bids}/sub-qc/func/sub-qc_task-rest_bold.nii")
print("Done.")
