#!/bin/bash

/cm/shared/singularity/bin/singularity run -c \
  -B /home/ddrucker/mictools:/mictools:ro \
  -B /data/pipeline:/data/pipeline \
  /cm/shared/singularity/images/dcm.sif \
     storescp --output-directory /data/pipeline \
              --verbose \
              --sort-on-patientname \
              --eostudy-timeout 10 \
              --aetitle MICCPIPE \
              --exec-on-eostudy '/mictools/miccpipe/receiver-eostudy #p' \
              11050
