name: iris-fmriprep

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y unzip curl
        curl -L -o /tmp/dcm2niix_lnx.zip https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20241211/dcm2niix_lnx.zip
        unzip /tmp/dcm2niix_lnx.zip -d /tmp
        sudo mv /tmp/dcm2niix /usr/bin/
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pyyaml nipype
    - name: Lint with flake8
      run: |
        flake8 iris --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 iris --count --exit-zero --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest iris
